language: python
python:
- '3.8'
install:
- pip install -r requirements-dev.txt
script:
- flake8 .
deploy:
  provider: s3
  access_key_id:
    secure: H/Bqmk1kRLv7ZFFf5hGugR/eLMkmKQD44uwtl7jgUY2W35GAgiz2EJvGdTRlKgG0RZMenuRvRecB0cWmYuCdKpk1IkZKe+Bd+4q1zCpTf0HZPCAknrrSr5tRKwjdqMm7r1rHzl7WDX9wQvaLPIbPcuNJKsL5iw9QgPzMo1rOn10Wwk69Qk5plPjRKXlCkXt9x03A3nfu9CBgGo/RSv7SjEPC0K9VhPafbgigDpv0EqVIBEjIEYhceJC04Q/Yy+Oo8OXOn8NJO14xeYI3jpwMPJ3mDUW4TCBJfzyroBLCcxYLkxr/Ink66dEpFmw7+/F77e+CaS98TQbESB5u/R55Eq+dhUSAfba94eptzxgI+oXss/MjrnibISTmJeiwRhj2pfvt6whn2pNLgh9qKEzTDHbzsyz+srWE5HgHnKgaN0iHtA8o9D2zIEEw7N8OaWdDaKl6kDrWTOvS7QUUcjva0LQS+Ky8qb9ZTgXIj63a4fejQHX1UPWhYuv+AYTRlMLym5/ftr2AC7ud4hmHF8/yapkFmXGcRJtVUbVycSeJ/jhtdyobALAGVAfaVH1rX41780ygfGTEDS59yjHBPJ4XaYmeeCbt9x4Kh0qcAKtSDdVYcgPdrcoJQdXtzvQ+0sfDa5Vj8iR+V+v/xiERl35Fgd3yr59S6+19QIvOCld5EOI=
  secret_access_key:
    secure: E/GsXa+eJ9UNHuVN3zAN05XfhSo3b7uQnVsGn3427BTiN9w3KtjsfZty1DxGxJDuUF4mUF5fD+0oHOOJRnUgXFEK2egTJG9LkjtrJN1TUuBEjk8lUrVSdVwxIqSCT3ZAhTQlrCKoVPvC+UwxYrrOMU7fIZhegBJcH4azaZo29QK57C1OpAQSW3FxA0hHYleGNOsu0TJnhNJiZ6Z4IYBwdmvD3+yEZnda5vgaBvyEZrQ1KIqU6ikCH+gUitvAep/XFayeVmbdt3IoLljcXl/BvOoXUAtGHpzQp3WufYAV0jYCfk9ngfwx2SotJG2CWuViIEXpI3xpAFvJt4YI9Vpz8D8CPOOOrUyWAeULdoPgBvonVjQOTpatCQALvtpG+dqpu4+OMYHYBT/+azzAckpSeQ9fv6Rjbm6LaV6dE1Pozbpj4pc98x51HiZqhuNTIqn2hwAIpRqYyuWmXoZ+XnxaJqYNsFR/tvhupMrOyY3J9GsYiBQLRKPKyQBaX6Tgqnbwq3+hBWVBog5k0wYyOuMQ4JKAjT1TuAJfWvlPU6OenDTR9kkX8ercmF2Kg06srcXIEptIrROIh6nbahoH1wDf0B8vuvnN/YkOeWspEVrXiQl2IEPAMlTc1KDZrMmz39l9p4Z2fIakC1aGgCtH5zM87YyZeiN/9dqFFHZTVzGktm0=   
  bucket: www.compilers.live
  skip_cleanup: true
  glob: "static/*"
